authors:
- Jules
- Jason Miller <jason.miller@thoughtparameters.com>
description: A collection of Ansible roles, playbooks, and modules for common DevOps
  tasks.
license:
- MIT
name: devops
namespace: thoughtparametersllc
readme: README.md
repository: https://github.com/ThoughtParameters/ansible.devops.collection
tags:
- devops
- automation
- infrastructure
version: 0.0.2
