# galaxy.yml
namespace: thoughtparametersllc
name: devops
version: 1.0.0
readme: README.md
authors:
  - "Jules"
  - "Jason Miller <jason.miller@thoughtparameters.com>"
description: "A collection of Ansible roles, playbooks, and modules for common DevOps tasks."
license:
  - MIT
tags:
  - devops
  - automation
  - infrastructure
repository: "https://github.com/ThoughtParameters/ansible.devops.collection"
