name: CI
on:
  pull_request:
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: |
          pip install ansible ansible-lint molecule molecule-docker

      - name: Install antsibull-changelog
        run: |
          pip install antsibull-changelog

      - name: Changelog Linting
        run: |
          antsibull-changelog lint

      - name: Linting
        run: |
          ansible-lint

      - name: Run molecule tests
        run: |
          cd roles/docker && molecule test
