name: Publish to Ansible Galaxy
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install ansible

      - name: Build and publish to Galaxy
        run: |
          ansible-galaxy collection build
          ansible-galaxy collection publish --api-key ${{ secrets.GALAXY_API_KEY }} $(find . -name "thoughtparametersllc-devops-*.tar.gz" -type f)
