name: Publish Collection via Release Tarball to Ansible Galaxy

on:
  release:
    types: [published]

jobs:
  publish_from_release:
    runs-on: ubuntu-latest
    steps:
      - name: Download release tarball artifact
        # Use the GitHub CLI or wget/curl to grab the tarball from GitHub release
        run: |
          # The name of the tarball might follow a known convention; adjust as needed
          # For example: my_namespace-my_collection-${{ github.ref_name }}.tar.gz
          TAG=${GITHUB_REF/refs\/tags\//}
          ARTIFACT="thoughtparametersllc-devops-${TAG}.tar.gz"
          # Use GitHub API to fetch the release asset
          # Requires permissions and possibly a token
          curl -L --fail \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -o "$ARTIFACT" \
            "https://github.com/${{ github.repository }}/releases/download/${TAG}/${ARTIFACT}"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Publish collection to Galaxy
        env:
          GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          ARTIFACT="thoughtparametersllc-devops-${TAG}.tar.gz"
          ansible-galaxy collection publish "$ARTIFACT" --api-key "$GALAXY_API_KEY"

